# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b3df8822f9e2ec6d85ebfb9894d96d2813bdf78469ebd541653613532b8886ffc048a35526b93583ecc7b95484a5bc941fffd06d1cd8103dc3e65bf3cafb60

test:
  secret_key_base: 3fe48cc9a255126114df146e70d84089cfe24a58569daf1783e3c0e4f2070fcda854b28ddda8ac0d91b88f24de77913c599c4acafdfc8fdf8d72ba52d37efcb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
